name: Bug report
description: Create a bug report to help us improve.
labels: [ 'bug' ]
type: bug

body:
  - type: input
    attributes:
      label: Minecraft
      description: What version of Minecraft are you using?
      placeholder: e.g., Minecraft 1.21.4
    validations:
      required: true

  - type: input
    attributes:
      label: Pack Version
      description: What version of the pack are you using?
      placeholder: e.g., 7.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Mods, if applicable?
      description: |
        If you're using any mods, please give a plain text list or log here.
        
        Please include:
          - The mod loader you are using
          - The name of each mod
          - The version of each mod
      placeholder: e.g., Fabric 0.16.10, followed by your mod list
    validations:
      required: false

  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: input
    attributes:
      label: Expected results
      description: What behavior did you expect?
      placeholder: e.g., the title to be gayly textured.
    validations:
      required: true

  - type: input
    attributes:
      label: Actual results
      description: What behavior did you observe instead?
      placeholder: e.g., the title is warped.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: Crash reports, server logs, screenshots, and videos should go here.
    validations:
      required: false
